environment:
  matrix:
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test

build: off
